### ISSUE TITLE
Are you even tested with code?

### ISSUE THREAD

**Issue by lucasjinreal** [thomasantony/llamacpp-python#23]
```
src/llamacpp/cli.py", line 196, in main
    if args.interactive and model.is_finished():
AttributeError: 'llamacpp.llamacpp.LlamaInference' object has no attribute 'is_finished'
```

**Comment by thomasantony** [comment]
`cli.py` is a bit outdated at this point. I have been a bit swamped with other work and haven't had a chance to bring it up to date given how fast llama.cpp has been getting updated.

**Comment by lucasjinreal** [comment]
@thomasantony the params is async with your wrapper not llama.cpp it self. Could u please note this in readme that not work at all otherwise users just waste time on your implementation.
