### ISSUE TITLE
Better support for editable install

### ISSUE THREAD

**Issue by JohannesGaessler** [thomasantony/llamacpp-python#26]
I am not a lamacpp-python user but I used it for tracking down a llama.cpp VRAM leak. For this I installed llamacpp-python as editable via `pip3 install -e .` . This caused some issues with the Python module not finding `libllama.so` but I was able to fix it by just symlinking it. Instructions in the README for how to do an editable install may be useful (but more experienced developers should be able to do this even without instructions).

**Comment by thomasantony** [comment]
Do editable installs work with compiled modules though? I was not aware of that. Please make a PR if you know how to do it!

**Comment by JohannesGaessler** [comment]
I'm not super knowledgeable about it either; I was just thinking that instructions would be useful.

**Comment by JohannesGaessler** [comment]
Sorry for the confusion, it seems I confused this repository with this one: https://github.com/abetlen/llama-cpp-python
